### ISSUE TITLE
matebook14 2019黑苹果

### ISSUE THREAD

**Issue by shenhfhep** [andrewlsa/Matebook-14-2019#2]
老哥你好,我用的也是matebook14 2019款, 目前黑苹果(bigsur)用了ske1996 大佬的efi,可以盒盖再打开,就唤醒不了,不知道你有没有遇到过同样的问题.还有可否发一份你自用efi给我,十分感谢

**Comment by andrewlsa** [comment]
> 老哥你好,我用的也是matebook14 2019款, 目前黑苹果(bigsur)用了ske1996 大佬的efi,可以盒盖再打开,就唤醒不了,不知道你有没有遇到过同样的问题.还有可否发一份你自用efi给我,十分感谢

等我有空上传一下。

**Comment by shenhfhep** [comment]
> > 老哥你好,我用的也是matebook14 2019款, 目前黑苹果(bigsur)用了ske1996 大佬的efi,可以盒盖再打开,就唤醒不了,不知道你有没有遇到过同样的问题.还有可否发一份你自用efi给我,十分感谢
> 
> 等我有空上传一下。
多谢
